POST http://localhost:3000/order/create
Content-Type: application/json

{
  "status": "pending",
  "total": 100,
  "products": [
    {
      "id": 5,
      "name": "Product 5",
      "weight": 10,
      "price": 10
    },
    {
      "id": 4,
      "name": "Product 5",
      "weight": 10,
      "price": 10
    }
  ]
}
